server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: [email]
    password: [password]
    properties: 
      mail:
        smtp:
          starttls:
              enable: true
              required: true
          auth: true
          
  datasource:
    driver-class-name: org.postgresql.Driver
    url: [url]
    username: postgres
    password: [password]
    hikari:
      data-source-properties:
        serverTimezone: UTC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      javax.persistence.validation.mode: none

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 500MB

s3:
  endpointUrl: https://s3.amazonaws.com
  accessKeyId: [accessKeyId]
  secretKey: [secretKey]
  bucketName: baligongbuckettest
  region: eu-west-1
